# fly.toml app configuration file generated for noray on 2025-04-20T09:56:46-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "noray"
build = { }
primary_region = "dfw"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 8891
min_machines_running = 0
processes = [ "app" ]

[[services]]
  internal_port = 8890
  protocol = "tcp"
  [[services.ports]]
    port = 8890

[[services]]
  internal_port = 8809
  protocol = "udp"
  [[services.ports]]
    port = 8809

[[services]]
  internal_port = 49152
  protocol = "udp"
  [[services.ports]]
    port = 49152

[[vm]]
size = "shared-cpu-1x"
